/*TOPIC_TYPE*/
CREATE TABLE `vital`.`TOPIC_TYPE`
( 	`TOPIC_TYPE_ID` INT NOT NULL AUTO_INCREMENT,
	`TOPIC_TYPE_NAME` VARCHAR(30),
	`TOPIC_TYPE_DESC` VARCHAR(255), 
	PRIMARY KEY (`TOPIC_TYPE_ID`) ); 
	
	
CREATE TABLE `vital`.`CONTENT_STYLES`
( 	`STYLE_ID` INT NOT NULL AUTO_INCREMENT, 
	`STYLE_NAME` VARCHAR(30), 
	`CSS_FILE` VARCHAR(255), 
	`PHP_FILE` VARCHAR(255), 
	PRIMARY KEY (`STYLE_ID`) ); 

	
CREATE TABLE `vital`.`CONTENT_TOPIC`
( 	`CONTENT_TOPIC_ID` INT NOT NULL AUTO_INCREMENT, 
	`TITLE` VARCHAR(100), 
	`SHORT_DESC` TEXT, 
	`LONG_DESC` TEXT, 
	`STYLE_ID` INT, 
	`TOPIC_TYPE_ID` INT, 
	PRIMARY KEY (`CONTENT_TOPIC_ID`) ); 

ALTER TABLE `vital`.`CONTENT_TOPIC` 
	ADD CONSTRAINT `TOP_TYPE` FOREIGN KEY (`TOPIC_TYPE_ID`) REFERENCES `vital`.`topic_type`(`TOPIC_TYPE_ID`), 
	ADD CONSTRAINT `TOP_STYLE` FOREIGN KEY (`STYLE_ID`) REFERENCES `vital`.`content_styles`(`STYLE_ID`); 
