/* CREATE DATABASE*/
CREATE DATABASE `vital` CHARACTER SET utf8 COLLATE utf8_unicode_ci; 

USE 'vital';

/*CREATE DB USER*/
CREATE USER 'vitalconn'@'localhost' IDENTIFIED BY 'P@ssword123'; 
GRANT ALL PRIVILEGES ON *.* TO 'vitalconn'@'%' IDENTIFIED BY 'P@ssword123' WITH GRANT OPTION; 
GRANT ALL PRIVILEGES ON *.* TO 'vitalconn'@'localhost' IDENTIFIED BY 'P@ssword123' WITH GRANT OPTION;


CREATE TABLE `members` (
  `USER_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  `username` VARCHAR(30) NOT NULL,   
  `password` CHAR(128) NOT NULL, 
  `salt` CHAR(128) NOT NULL
) ENGINE = InnoDB;


CREATE TABLE `LOGIN_ATTEMPTS` (
  `USER_ID` INT(11) NOT NULL,
  `TIME` VARCHAR(30) NOT NULL 
) ENGINE=INNODB