/*TOPIC_TYPE*/

USE 'VITAL';

CREATE TABLE `TOPIC_TYPE`
( 	`TOPIC_TYPE_ID` INT NOT NULL AUTO_INCREMENT,
	`TOPIC_TYPE_NAME` VARCHAR(30),
	`TOPIC_TYPE_DESC` VARCHAR(255),
	`TOPIC_DISPLAY_NAME` VARCHAR(20)
	PRIMARY KEY (`TOPIC_TYPE_ID`) ); 
	
	
CREATE TABLE `CONTENT_STYLES`
( 	`STYLE_ID` INT NOT NULL AUTO_INCREMENT, 
	`STYLE_NAME` VARCHAR(30), 
	`CSS_FILE` VARCHAR(255), 
	`PHP_FILE` VARCHAR(255), 
	PRIMARY KEY (`STYLE_ID`) ); 

	
CREATE TABLE `CONTENT_TOPIC`
( 	`CONTENT_TOPIC_ID` INT NOT NULL AUTO_INCREMENT, 
	`TITLE` VARCHAR(100), 
	`SHORT_DESC` TEXT, 
	`LONG_DESC` TEXT, 
	`STYLE_ID` INT, 
	`TOPIC_TYPE_ID` INT, 
	PRIMARY KEY (`CONTENT_TOPIC_ID`) ); 

CREATE TABLE `TOPIC_STYLE`
( 	`STYLE_ID` INT NOT NULL AUTO_INCREMENT, 
	`HEADER_CSS_CLASS` VARCHAR(126), 
	`BODY_CSS_CLASS` VARCHAR(126), 
	PRIMARY KEY (`STYLE_ID`) ) ENGINE=INNODB;
	
CREATE TABLE `TOPIC_STYLE_LINK`
( 	`CONTENT_TOPIC_ID` INT, 
	`STYLE_ID` INT, 
	CONSTRAINT `content_topic_link` FOREIGN KEY (`CONTENT_TOPIC_ID`) REFERENCES `content_topic`(`CONTENT_TOPIC_ID`), 
	CONSTRAINT `style_link` FOREIGN KEY (`STYLE_ID`) REFERENCES `topic_style`(`STYLE_ID`) ) ENGINE=INNODB; 
	

ALTER TABLE `CONTENT_TOPIC` 
	ADD CONSTRAINT `TOP_TYPE` FOREIGN KEY (`TOPIC_TYPE_ID`) REFERENCES `topic_type`(`TOPIC_TYPE_ID`), 
	ADD CONSTRAINT `TOP_STYLE` FOREIGN KEY (`STYLE_ID`) REFERENCES `content_styles`(`STYLE_ID`); 

